"""Add title review

Revision ID: 716f446d9c6f
Revises: 0ff2a75f8823
Create Date: 2026-09-29 14:31:13.063015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716f446d9c6f'
down_revision: Union[str, Sequence[str], None] = '0ff2a75f8823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'title')
    # ### end Alembic commands ###
